name: CI pipeline for Graasp research

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  graasp-deploy-s3-workflow:
    name: Graasp Analyzer
    uses: graasp/graasp-deploy/.github/workflows/cintegration-s3.yml@main
    with:
      build-folder: 'build'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-region: ${{ secrets.AWS_REGION_DEV }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_GRAASP_RESEARCH_DEV }}
      cloudfront-distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_GRAASP_RESEARCH_DEV }}
      api-host: ${{ secrets.REACT_APP_API_HOST_DEV }}
      google-key: ${{ secrets.REACT_APP_GOOGLE_KEY_DEV }}
