import { Item } from '@graasp/sdk';

const MOCK_ITEMS: Item[] = [
  {
    id: '1111-bbbb',
    name: 'folder1',
    path: '1111_bbbb',
    type: 'folder',
    description: null,
    settings: {},
    extra: {},
    creator: 'user1',
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: '2222-bbbb',
    name: 'folder2',
    path: '1111_bbbb.2222_bbbb',
    type: 'folder',
    description: null,
    settings: {},
    extra: {},
    creator: 'user1',
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: '1234-abcd',
    name: 'document1',
    path: '1234_abcd',
    type: 'document',
    description: null,
    settings: {},
    extra: {},
    creator: 'user1',
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: '5678-abcd',
    name: 'document2',
    path: '1111_bbbb.2222_bbbb.5678_abcd',
    type: 'document',
    description: null,
    settings: {},
    extra: {},
    creator: 'user1',
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: '1111-kkkk',
    name: 'folder3',
    path: '1111_kkkk',
    type: 'folder',
    description: null,
    settings: {},
    extra: {},
    creator: 'user2',
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: '1234-kkkk',
    name: 'sharedFolder1',
    path: '1111_kkkk.1234_kkkk',
    type: 'folder',
    description: null,
    settings: {},
    extra: {},
    creator: 'user2',
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: '5678-kkkk',
    name: 'sharedDocument1',
    path: '1111_kkkk.1234_kkkk.5678_kkkk',
    type: 'document',
    description: null,
    settings: {},
    extra: {},
    creator: 'user2',
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
];

export default MOCK_ITEMS;
